-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-10-14 13:51:44 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE


 CREATE SEQUENCE  "NEXT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE TABLE bonus_payout (
    id_employee      NUMBER(3) default "NEXT_ID"."NEXTVAL" NOT NULL,
    date_payout      DATE,
    bonus_salary_pln NUMBER(5),
    id_bonus         NUMBER(2) NOT NULL
);

ALTER TABLE bonus_payout ADD CONSTRAINT bonus_payout_pk PRIMARY KEY ( id_employee );

CREATE TABLE bonus_type (
    id_bonus          NUMBER(2) default "NEXT_ID"."NEXTVAL" NOT NULL,
    bonus_description VARCHAR2(100 CHAR)
);

ALTER TABLE bonus_type ADD CONSTRAINT bonus_type_pk PRIMARY KEY ( id_bonus );

CREATE TABLE e_tariffs (
    id_tariff      NUMBER(3) default "NEXT_ID"."NEXTVAL"
        CONSTRAINT nnc_e_tariffs_id_tariff NOT NULL,
    price_for_1kwh NUMBER(5, 2),
    date_start     DATE
);

ALTER TABLE e_tariffs ADD CONSTRAINT e_tariffs_pk PRIMARY KEY ( id_tariff );

CREATE TABLE elec_prod (
    id_measurement    NUMBER(5) default "NEXT_ID"."NEXTVAL"
        CONSTRAINT nnc_elec_prod_id_measurement NOT NULL,
    id_meter          NUMBER(3)
        CONSTRAINT nnc_elec_prod_id_meter NOT NULL,
    date_measurement  DATE,
    mater_reading_kwh NUMBER(8, 3),
    power_kwh         NUMBER(6, 2),
    id_tariff         NUMBER(3)
        CONSTRAINT nnc_elec_prod_id_tariff NOT NULL
);

ALTER TABLE elec_prod ADD CONSTRAINT elec_prod_pk PRIMARY KEY ( id_measurement );

CREATE TABLE elec_social (
    id_measurement    NUMBER(5) default "NEXT_ID"."NEXTVAL"
        CONSTRAINT nnc_elec_social_id_measurement NOT NULL,
    id_meter          NUMBER(3)
        CONSTRAINT nnc_elec_social_id_meter NOT NULL,
    date_measurement  DATE,
    meter_reading_kwh NUMBER(8, 3),
    power_kw          NUMBER(6, 2),
    id_tariff         NUMBER(3)
        CONSTRAINT nnc_elec_social_id_tariff NOT NULL
);

ALTER TABLE elec_social ADD CONSTRAINT elec_social_pk PRIMARY KEY ( id_measurement );

CREATE TABLE employees (
    employee_id     NUMBER(3) default "NEXT_ID"."NEXTVAL" NOT NULL,
    firs_name       VARCHAR2(15 CHAR),
    last_name       VARCHAR2(30 CHAR),
    date_start_work DATE,
    salary          NUMBER(6),
    date_of_birth   DATE
);

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( employee_id );

CREATE TABLE g_tariffs (
    id_tariffs   NUMBER(3) default "NEXT_ID"."NEXTVAL"
        CONSTRAINT nnc_g_tariffs_id_tariffs NOT NULL,
    price_for_1m3 NUMBER(5, 2),
    date_start   DATE
);

ALTER TABLE g_tariffs ADD CONSTRAINT g_tariffs_pk PRIMARY KEY ( id_tariffs );

CREATE TABLE gas_prod (
    id_measurement   NUMBER(5) default "NEXT_ID"."NEXTVAL"
        CONSTRAINT nnc_gas_prod_id_measurement NOT NULL,
    id_meter         NUMBER(3)
        CONSTRAINT nnc_gas_prod_id_meter NOT NULL,
    date_measurement DATE,
    meter_reading_m3 NUMBER(9, 3),
    id_tariffs       NUMBER(3)
        CONSTRAINT nnc_gas_prod_id_tariffs NOT NULL
);

ALTER TABLE gas_prod ADD CONSTRAINT gas_prod_pk PRIMARY KEY ( id_measurement );

CREATE TABLE gas_social (
    id_measurement   NUMBER(5) default "NEXT_ID"."NEXTVAL",
    id_meter         NUMBER(3) NOT NULL,
    date_measurement DATE,
    meter_reading_m3 NUMBER(9, 3),
    id_tariffs       NUMBER(3) NOT NULL
);

ALTER TABLE gas_social ADD CONSTRAINT gas_social_pk PRIMARY KEY ( id_tariffs );

CREATE TABLE meters (
    id_meter             NUMBER(3) default "NEXT_ID"."NEXTVAL" NOT NULL,
    name_meter           VARCHAR2(30 CHAR),
    model_meter          VARCHAR2(30 CHAR),
    person_inspection    NUMBER(3) NOT NULL,
    date_inspection      DATE,
    date_next_inspection DATE
);

ALTER TABLE meters ADD CONSTRAINT meters_pk PRIMARY KEY ( id_meter );

CREATE TABLE w_tariffs (
    id_tariff     NUMBER(3) default "NEXT_ID"."NEXTVAL"
        CONSTRAINT nnc_w_tariffs_id_tariff NOT NULL,
    price_for_1m3 NUMBER(5, 2),
    date_start    DATE
);

ALTER TABLE w_tariffs ADD CONSTRAINT w_tariffs_pk PRIMARY KEY ( id_tariff );

CREATE TABLE water_prod (
    id_measurement   NUMBER(5) default "NEXT_ID"."NEXTVAL"
        CONSTRAINT nnc_water_prod_id_measurement NOT NULL,
    id_meter         NUMBER(3)
        CONSTRAINT nnc_water_prod_id_meter NOT NULL,
    date_measurement DATE,
    meter_reading_m3 NUMBER(8, 3),
    id_tariff        NUMBER(3)
        CONSTRAINT nnc_water_prod_id_tariff NOT NULL
);

ALTER TABLE water_prod ADD CONSTRAINT water_prod_pk PRIMARY KEY ( id_measurement );

CREATE TABLE water_social (
    id_measurement   NUMBER(5) default "NEXT_ID"."NEXTVAL" NOT NULL,
    id_meter         NUMBER(3) NOT NULL,
    date_measurement DATE,
    meter_reading_m3 NUMBER(8, 3),
    id_tariff        NUMBER(3) NOT NULL
);

ALTER TABLE water_social ADD CONSTRAINT water_social_pk PRIMARY KEY ( id_measurement );

ALTER TABLE bonus_payout
    ADD CONSTRAINT bonus_payout_bonus_type_fk FOREIGN KEY ( id_bonus )
        REFERENCES bonus_type ( id_bonus );

ALTER TABLE bonus_payout
    ADD CONSTRAINT bonus_payout_employees_fk FOREIGN KEY ( id_employee )
        REFERENCES employees ( employee_id );

ALTER TABLE elec_prod
    ADD CONSTRAINT elec_prod_electric_tariffs_fk FOREIGN KEY ( id_tariff )
        REFERENCES e_tariffs ( id_tariff );

ALTER TABLE elec_prod
    ADD CONSTRAINT elec_prod_meters_fk FOREIGN KEY ( id_meter )
        REFERENCES meters ( id_meter );

ALTER TABLE elec_social
    ADD CONSTRAINT elec_social_elec_tariffs_fk FOREIGN KEY ( id_tariff )
        REFERENCES e_tariffs ( id_tariff );

ALTER TABLE elec_social
    ADD CONSTRAINT elec_social_meters_fk FOREIGN KEY ( id_meter )
        REFERENCES meters ( id_meter );

ALTER TABLE gas_prod
    ADD CONSTRAINT gas_prod_gas_tariffs_fk FOREIGN KEY ( id_tariffs )
        REFERENCES g_tariffs ( id_tariffs );

ALTER TABLE gas_prod
    ADD CONSTRAINT gas_prod_meters_fk FOREIGN KEY ( id_meter )
        REFERENCES meters ( id_meter );

ALTER TABLE gas_social
    ADD CONSTRAINT gas_social_gas_tariffs_fk FOREIGN KEY ( id_tariffs )
        REFERENCES g_tariffs ( id_tariffs );

ALTER TABLE gas_social
    ADD CONSTRAINT gas_social_meters_fk FOREIGN KEY ( id_meter )
        REFERENCES meters ( id_meter );

ALTER TABLE meters
    ADD CONSTRAINT meters_employees_fk FOREIGN KEY ( person_inspection )
        REFERENCES employees ( employee_id );

ALTER TABLE water_prod
    ADD CONSTRAINT water_prod_meters_fk FOREIGN KEY ( id_meter )
        REFERENCES meters ( id_meter );

ALTER TABLE water_prod
    ADD CONSTRAINT water_prod_water_tariffs_fk FOREIGN KEY ( id_tariff )
        REFERENCES w_tariffs ( id_tariff );

ALTER TABLE water_social
    ADD CONSTRAINT water_social_meters_fk FOREIGN KEY ( id_meter )
        REFERENCES meters ( id_meter );

ALTER TABLE water_social
    ADD CONSTRAINT water_social_water_tariffs_fk FOREIGN KEY ( id_tariff )
        REFERENCES w_tariffs ( id_tariff );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
