/*update 31-12-2023*/



CREATE SEQUENCE  "NEXT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


  CREATE TABLE "MMDS"."BONUS_PAYOUT" 
   (	"ID_EMPLOYEE" NUMBER(3,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" NOT NULL ENABLE, 
	"DATE_PAYOUT" DATE, 
	"BONUS_SALARY_PLN" NUMBER(5,0), 
	"ID_BONUS" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "BONUS_PAYOUT_PK" PRIMARY KEY ("ID_EMPLOYEE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 


	 CONSTRAINT "BONUS_PAYOUT_BONUS_TYPE_FK" FOREIGN KEY ("ID_BONUS")
	  REFERENCES "MMDS"."BONUS_TYPE" ("ID_BONUS") ENABLE, 
	 CONSTRAINT "BONUS_PAYOUT_EMPLOYEES_FK" FOREIGN KEY ("ID_EMPLOYEE")
	  REFERENCES "MMDS"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


  CREATE TABLE "MMDS"."BONUS_TYPE" 
   (	"ID_BONUS" NUMBER(2,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" NOT NULL ENABLE, 
	"BONUS_DESCRIPTION" VARCHAR2(100 CHAR), 
	 CONSTRAINT "BONUS_TYPE_PK" PRIMARY KEY ("ID_BONUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  CREATE TABLE "MMDS"."E_TARIFFS" 
   (	"ID_TARIFF" NUMBER(*,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" CONSTRAINT "NNC_E_TARIFFS_ID_TARIFF" NOT NULL ENABLE, 
	"PRICE_FOR_1KWH" NUMBER(5,2), 
	"DATE_START" DATE, 
	 CONSTRAINT "E_TARIFFS_PK" PRIMARY KEY ("ID_TARIFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



CREATE TABLE "MMDS"."ELEC_PROD" 
   (	"ID_MEASUREMENT" NUMBER(5,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" CONSTRAINT "NNC_ELEC_PROD_ID_MEASUREMENT" NOT NULL ENABLE, 
	"ID_METER" NUMBER(3,0) CONSTRAINT "NNC_ELEC_PROD_ID_METER" NOT NULL ENABLE, 
	"DATE_MEASUREMENT" DATE, 
	"METER_READING_KWH" NUMBER(8,3), 
	"POWER_KWH" NUMBER(6,2), 
	"ID_TARIFF" NUMBER(3,0) CONSTRAINT "NNC_ELEC_PROD_ID_TARIFF" NOT NULL ENABLE, 
	 CONSTRAINT "ELEC_PROD_PK" PRIMARY KEY ("ID_MEASUREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ELEC_PROD_ELECTRIC_TARIFFS_FK" FOREIGN KEY ("ID_TARIFF")
	  REFERENCES "MMDS"."E_TARIFFS" ("ID_TARIFF") ENABLE, 
	 CONSTRAINT "ELEC_PROD_METERS_FK" FOREIGN KEY ("ID_METER")
	  REFERENCES "MMDS"."METERS" ("ID_METER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MMDS"."BI_ELEC_PROD" BEFORE
    INSERT ON elec_prod
    FOR EACH ROW
DECLARE
    v_id_tariff e_tariffs.id_tariff%TYPE;
BEGIN
    SELECT
        id_tariff
    INTO v_id_tariff
    FROM
        e_tariffs
    WHERE
        :new.date_measurement >= date_start
    ORDER BY
        date_start
    FETCH FIRST 1 ROW ONLY;

    :new.id_tariff := v_id_tariff;

EXCEPTION

WHEN no_data_found then
dbms_output.put_line('No tariff has been specified for the date entered');

END bi_elec_prod;
/
ALTER TRIGGER "MMDS"."BI_ELEC_PROD" ENABLE;





  CREATE TABLE "MMDS"."ELEC_SOCIAL" 
   (	"ID_MEASUREMENT" NUMBER(5,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" CONSTRAINT "NNC_ELEC_SOCIAL_ID_MEASUREMENT" NOT NULL ENABLE, 
	"ID_METER" NUMBER(3,0) CONSTRAINT "NNC_ELEC_SOCIAL_ID_METER" NOT NULL ENABLE, 
	"DATE_MEASUREMENT" DATE, 
	"METER_READING_KWH" NUMBER(8,3), 
	"POWER_KWH" NUMBER(6,2), 
	"ID_TARIFF" NUMBER(3,0) CONSTRAINT "NNC_ELEC_SOCIAL_ID_TARIFF" NOT NULL ENABLE, 
	 CONSTRAINT "ELEC_SOCIAL_PK" PRIMARY KEY ("ID_MEASUREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "ELEC_SOCIAL_ELEC_TARIFFS_FK" FOREIGN KEY ("ID_TARIFF")
	  REFERENCES "MMDS"."E_TARIFFS" ("ID_TARIFF") ENABLE, 
	 CONSTRAINT "ELEC_SOCIAL_METERS_FK" FOREIGN KEY ("ID_METER")
	  REFERENCES "MMDS"."METERS" ("ID_METER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MMDS"."BI_ELEC_SOCIAL" BEFORE
    INSERT ON elec_social
    FOR EACH ROW
DECLARE
    v_id_tariff e_tariffs.id_tariff%TYPE;
BEGIN
    SELECT
        id_tariff
    INTO v_id_tariff
    FROM
        e_tariffs
    WHERE
        :new.date_measurement >= date_start
    ORDER BY
        date_start
    FETCH FIRST 1 ROW ONLY;

    :new.id_tariff := v_id_tariff;

EXCEPTION

WHEN no_data_found then
dbms_output.put_line('No tariff has been specified for the date entered');


END bi_elec_social;
/
ALTER TRIGGER "MMDS"."BI_ELEC_SOCIAL" ENABLE;

CREATE TABLE "MMDS"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(3,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(15 CHAR), 
	"LAST_NAME" VARCHAR2(30 CHAR), 
	"DATE_START_WORK" DATE, 
	"SALARY" NUMBER(6,0), 
	"DATE_OF_BIRTH" DATE, 
	 CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE TABLE "MMDS"."G_TARIFFS" 
   (	"ID_TARIFF" NUMBER(3,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" CONSTRAINT "NNC_G_TARIFFS_ID_TARIFFS" NOT NULL ENABLE, 
	"PRICE_FOR_1M3" NUMBER(5,2), 
	"DATE_START" DATE, 
	 CONSTRAINT "G_TARIFFS_PK" PRIMARY KEY ("ID_TARIFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;





  CREATE TABLE "MMDS"."GAS_PROD" 
   (	"ID_MEASUREMENT" NUMBER(5,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" CONSTRAINT "NNC_GAS_PROD_ID_MEASUREMENT" NOT NULL ENABLE, 
	"ID_METER" NUMBER(3,0) CONSTRAINT "NNC_GAS_PROD_ID_METER" NOT NULL ENABLE, 
	"DATE_MEASUREMENT" DATE, 
	"METER_READING_M3" NUMBER(9,3), 
	"ID_TARIFF" NUMBER(3,0) CONSTRAINT "NNC_GAS_PROD_ID_TARIFFS" NOT NULL ENABLE, 
	"USE_CURRENT" NUMBER(9,3), 
	 CONSTRAINT "GAS_PROD_PK" PRIMARY KEY ("ID_MEASUREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "GAS_PROD_GAS_TARIFFS_FK" FOREIGN KEY ("ID_TARIFF")
	  REFERENCES "MMDS"."G_TARIFFS" ("ID_TARIFF") ENABLE, 
	 CONSTRAINT "GAS_PROD_METERS_FK" FOREIGN KEY ("ID_METER")
	  REFERENCES "MMDS"."METERS" ("ID_METER") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MMDS"."BI_GAS_PROD" BEFORE
    INSERT ON gas_prod
    FOR EACH ROW
DECLARE
    v_id_tariff g_tariffs.id_tariff%TYPE;
BEGIN
    SELECT
        id_tariff
    INTO v_id_tariff
    FROM
        g_tariffs
    WHERE
        :new.date_measurement >= date_start
    ORDER BY
        date_start
    FETCH FIRST 1 ROW ONLY;

    :new.id_tariff := v_id_tariff;


EXCEPTION

WHEN no_data_found then
dbms_output.put_line('No tariff has been specified for the date entered');

END bi_gas_prod_elec_prod;
/
ALTER TRIGGER "MMDS"."BI_GAS_PROD" ENABLE;






  CREATE TABLE "MMDS"."GAS_SOCIAL" 
   (	"ID_MEASUREMENT" NUMBER(5,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL", 
	"ID_METER" NUMBER(3,0) NOT NULL ENABLE, 
	"DATE_MEASUREMENT" DATE, 
	"METER_READING_M3" NUMBER(9,3), 
	"ID_TARIFFS" NUMBER(3,0) NOT NULL ENABLE, 
	"USE_CURRENT" NUMBER(9,3), 
	 CONSTRAINT "GAS_SOCIAL_PK" PRIMARY KEY ("ID_MEASUREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MMDS"."BI_GAS_SOCIAL" BEFORE
    INSERT ON gas_social
    FOR EACH ROW
DECLARE
    v_id_tariff g_tariffs.id_tariff%TYPE;
BEGIN
    SELECT
        id_tariff
    INTO v_id_tariff
    FROM
        g_tariffs
    WHERE
        :new.date_measurement >= date_start
    ORDER BY
        date_start
    FETCH FIRST 1 ROW ONLY;

    :new.id_tariffs := v_id_tariff;

EXCEPTION
    WHEN no_data_found THEN
        dbms_output.put_line('No tariff has been specified for the date entered');
END bi_gas_social;
/
ALTER TRIGGER "MMDS"."BI_GAS_SOCIAL" ENABLE;




  CREATE TABLE "MMDS"."GAS_SOCIAL" 
   (	"ID_MEASUREMENT" NUMBER(5,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL", 
	"ID_METER" NUMBER(3,0) NOT NULL ENABLE, 
	"DATE_MEASUREMENT" DATE, 
	"METER_READING_M3" NUMBER(9,3), 
	"ID_TARIFFS" NUMBER(3,0) NOT NULL ENABLE, 
	"USE_CURRENT" NUMBER(9,3), 
	 CONSTRAINT "GAS_SOCIAL_PK" PRIMARY KEY ("ID_MEASUREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MMDS"."BI_GAS_SOCIAL" BEFORE
    INSERT ON gas_social
    FOR EACH ROW
DECLARE
    v_id_tariff g_tariffs.id_tariff%TYPE;
BEGIN
    SELECT
        id_tariff
    INTO v_id_tariff
    FROM
        g_tariffs
    WHERE
        :new.date_measurement >= date_start
    ORDER BY
        date_start
    FETCH FIRST 1 ROW ONLY;

    :new.id_tariffs := v_id_tariff;

EXCEPTION
    WHEN no_data_found THEN
        dbms_output.put_line('No tariff has been specified for the date entered');
END bi_gas_social;
/
ALTER TRIGGER "MMDS"."BI_GAS_SOCIAL" ENABLE;




  CREATE TABLE "MMDS"."RAPORT_8H_PROD" 
   (	"ID_NR" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DATA_START" DATE, 
	"DATA_END" DATE, 
	"ELEC_KWH" NUMBER(9,3), 
	"WATHER_M3" NUMBER(9,3), 
	"GAS_M3" NUMBER(9,3), 
	"PRICE_ELEC" NUMBER(9,3), 
	"PRICE_WATER" NUMBER(9,3), 
	"PRICE_GAS" NUMBER(9,3), 
	 PRIMARY KEY ("ID_NR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



  CREATE TABLE "MMDS"."W_TARIFFS" 
   (	"ID_TARIFF" NUMBER(3,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" CONSTRAINT "NNC_W_TARIFFS_ID_TARIFF" NOT NULL ENABLE, 
	"PRICE_FOR_1M3" NUMBER(5,2), 
	"DATE_START" DATE, 
	 CONSTRAINT "W_TARIFFS_PK" PRIMARY KEY ("ID_TARIFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;



  CREATE TABLE "MMDS"."WATER_PROD" 
   (	"ID_MEASUREMENT" NUMBER(5,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" CONSTRAINT "NNC_WATER_PROD_ID_MEASUREMENT" NOT NULL ENABLE, 
	"ID_METER" NUMBER(3,0) CONSTRAINT "NNC_WATER_PROD_ID_METER" NOT NULL ENABLE, 
	"DATE_MEASUREMENT" DATE, 
	"METER_READING_M3" NUMBER(8,3), 
	"ID_TARIFF" NUMBER(3,0) CONSTRAINT "NNC_WATER_PROD_ID_TARIFF" NOT NULL ENABLE, 
	"USE_CURRENT" NUMBER(9,3), 
	 CONSTRAINT "WATER_PROD_PK" PRIMARY KEY ("ID_MEASUREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WATER_PROD_METERS_FK" FOREIGN KEY ("ID_METER")
	  REFERENCES "MMDS"."METERS" ("ID_METER") ENABLE, 
	 CONSTRAINT "WATER_PROD_WATER_TARIFFS_FK" FOREIGN KEY ("ID_TARIFF")
	  REFERENCES "MMDS"."W_TARIFFS" ("ID_TARIFF") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MMDS"."BI_WATER_PROD" BEFORE
    INSERT ON water_prod
    FOR EACH ROW
DECLARE
    v_id_tariff g_tariffs.id_tariff%TYPE;
BEGIN
    SELECT
        id_tariff
    INTO v_id_tariff
    FROM
        w_tariffs
    WHERE
        :new.date_measurement >= date_start
    ORDER BY
        date_start
    FETCH FIRST 1 ROW ONLY;

    :new.id_tariff := v_id_tariff;

EXCEPTION
    WHEN no_data_found THEN
        dbms_output.put_line('No tariff has been specified for the date entered');
END bi_water_prod;
/
ALTER TRIGGER "MMDS"."BI_WATER_PROD" ENABLE;



  CREATE TABLE "MMDS"."WATER_SOCIAL" 
   (	"ID_MEASUREMENT" NUMBER(5,0) DEFAULT "MMDS"."NEXT_ID"."NEXTVAL" NOT NULL ENABLE, 
	"ID_METER" NUMBER(3,0) NOT NULL ENABLE, 
	"DATE_MEASUREMENT" DATE, 
	"METER_READING_M3" NUMBER(8,3), 
	"ID_TARIFF" NUMBER(3,0) NOT NULL ENABLE, 
	"USE_CURRENT" NUMBER(9,3), 
	 CONSTRAINT "WATER_SOCIAL_PK" PRIMARY KEY ("ID_MEASUREMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WATER_SOCIAL_METERS_FK" FOREIGN KEY ("ID_METER")
	  REFERENCES "MMDS"."METERS" ("ID_METER") ENABLE, 
	 CONSTRAINT "WATER_SOCIAL_WATER_TARIFFS_FK" FOREIGN KEY ("ID_TARIFF")
	  REFERENCES "MMDS"."W_TARIFFS" ("ID_TARIFF") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "MMDS"."BI_WATER_SOCIAL" BEFORE
    INSERT ON water_social
    FOR EACH ROW
DECLARE
    v_id_tariff g_tariffs.id_tariff%TYPE;
BEGIN
    SELECT
        id_tariff
    INTO v_id_tariff
    FROM
        w_tariffs
    WHERE
        :new.date_measurement >= date_start
    ORDER BY
        date_start
    FETCH FIRST 1 ROW ONLY;

    :new.id_tariff := v_id_tariff;

EXCEPTION
    WHEN no_data_found THEN
        dbms_output.put_line('No tariff has been specified for the date entered');


END bi_water_social;
/
ALTER TRIGGER "MMDS"."BI_WATER_SOCIAL" ENABLE;




